
name: Adenigbagbe Adewole
title: Adenigbagbe Adewole
description: "Adenigbagbe Adewole's blog about programming - C#, Golang, Typescript, Javascript."
url: https://adewoleadenigbagbe.github.io
baseurl: /blog
highlighter: rouge
permalink: /posts/:title/
markdown: kramdown

theme_options:
  google_analytics: G-241HN9TB7S

feed:
  categories:
    - csharp
    - golang
    - typescript
    - javascript

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
