# Site settings
title: "Adewole Charles Blog"
description: "Deep dives into C#, .NET internals, async/await, EF Core, and performance."
baseurl: "/blog"
url: "https://adewoleadenigbagbe.github.io/"

# Chirpy Theme
remote_theme: cotes2020/jekyll-theme-chirpy
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

# Dark Mode
theme_mode: # leave empty â†’ system preference, toggle visible

# Sidebar options
sidebar:
  profile: true
  about: true
  categories: true
  tags: true
  social_links: true

sidebar_pages:
  - title: "Archives"
    url: /archives/